### PR TITLE
v0.5.1

### PR DESCRIPTION
**Pull request by tlambert03**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tlambert03** [comment]
@conda-forge-admin, please rerender

**Comment by tlambert03** [comment]
sorry to bug you with basic conda stuff @jakirkham ... but can you tell why this didn't trigger a new version on on conda when I merged it to main?

**Comment by jakirkham** [comment]
Looks like CI did not run. Manually [started CI]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1005551&view=results )

**Comment by jakirkham** [comment]
Appears CI passed. Am seeing packages on Anaconda.org now. Guessing this is resolved?


Screenshot 2024-08-19 at 5 40 10 PM

**Comment by tlambert03** [comment]
yep perfect thank you.  may I ask where you looked to see this?  it clearly worked... but I'm struggling to see the difference between 

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1002849

and 

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1005551

**Comment by jakirkham** [comment]
The first is a build for this PR

<details>
Screenshot 2024-08-19 at 6 04 23 PM
</details>

The second is a build on `main`

<details>
Screenshot 2024-08-19 at 6 04 03 PM
</details>

Edit: To add screenshots with relevant text hightlighted in light blue

**Comment by tlambert03** [comment]
doh 🤦‍♂️ thank you for pointing that obvious thing out...

which github-side workflow triggers that, is it automerge?  and presumably something failed to send to azure on job 23 below, that succeeded for whatever reason on the manual trigger?

Screenshot 2024-08-20 at 8 58 21 AM

**Comment by jakirkham** [comment]
If you click the green checkmark (or red x) next to any commit, it will show the CI status (on Azure or other providers). Can then just follow that through

Screenshot 2024-08-20 at 2 10 43 PM

**Comment by tlambert03** [comment]
ok, thanks again!
i know that probably felt 101, but i hadn't yet grocked exactly how merging to main was actually connected to the azure builds.  cheers

**Comment by jakirkham** [comment]
Also if there is no check or x, would look at [the CI providers in the feedstock README]( https://github.com/conda-forge/pycudadecon-feedstock?tab=readme-ov-file#current-build-status ) and click those badges to learn what is happening

**Pull request merged**
